language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  app: boiling-tor-70749
  api_key:
    secure: P34ouhizV6zbM2OKl7ekZ+jg+mFfQxISXBxgDZ3p1/IViw7XU4dQPX9h9qBPw+VtGy2nM23X4RCHrRLK4/m4zvnooT5nz9ZACpklJW4FA65F88x3MmBs3DUwj80i7h9IErrFrTZo8JGHPReGaw4QivgUSCawlB7LjTqvAlf/HGkvapgkFWhTdxlBMaywpagJs7AdO+5btZrzkeZedBD2AEJY7PdBevmloNSBlJViKxwpRw69ZjdmlIea1vZnLjp1Q+sBe/h0GyNvCiP5N/SyRjZbqPs3xHKc5k4u7x5EIlYgZR5htK1DbDL+RLNR1DMbT6db6sbcWKNy3hxJOPYmxDkpk+Bo8x1WoCZAJnvb6V4CmM8xZR61ojxgZoNubWSFI6tE2/ldrlz35m5NNtMiGE32Da8bHUsLA6EIqQ2B9fpTZrS0sLzmp6NSFM89GwtvyUxAL6cfiSr9A2orlF46BvdadLJ3lVKH/SNrzsfyGL57mnYznX/epS2r/s9kHq9GKQJRy9qwGVTG6FkvAmpTRDSJtFTrLKWTgOQ4EpfiGmaLcvTxciiwoowQsVPwbs4iuT3mAZ5MPy16eelq+o9v2ykNU2jYgcsV0RdMJXPwM55rnv/liYK+vqxHK/53yCbI7xnCJUz14MtB3GwgTnv/gahE3A0Ce6rnDNXllitwuH8=
